module.exports = {
    menu: "menu",
    user: "test_user",
    category: "category",
    subcategory: "subcategory",
    cartItem: "cart_item",
    coupon: "coupon",
    product: "product",
    eligibleItem: "eligible_item",
    choice: "choice",
    option: "option",
    topping: "topping",
    ingredient: "ingredient",
    fields: "fields",
    choiceSet: "choice_set",
    optionSet: "option_set",
    toppingSet: "topping_set",
    ingredientSet: "ingredient_set",
    default_ingredients: "default_ingredients",
    default_options: "default_options"
}